// Caption domain types shared between the content script (producer) and the
// side panel (consumer). The content script imports these `import type`-only,
// so this module's runtime helper (findActiveCueIndex) never gets bundled into
// the classic content script — it ends up only in the side panel bundle.

/** A single timed subtitle line. */
export interface CaptionCue {
  id: string;
  /** Start time in seconds. */
  start: number;
  /** End time in seconds. */
  end: number;
  /** end - start, in seconds. */
  duration: number;
  /** Cleaned, display-ready text. */
  text: string;
}

/** Metadata for an available caption track on a video. */
export interface CaptionTrack {
  languageCode: string;
  name: string;
  /** YouTube's track kind; "asr" means auto-generated speech recognition. */
  kind?: string;
  isAutoGenerated?: boolean;
  /** Base timedtext URL used to fetch the cues. */
  url: string;
}

export type CaptionStatus = 'idle' | 'loading' | 'ready' | 'not_found' | 'error';

/**
 * `error` is a short machine-ish reason (e.g. "no_tracks", "no_spanish",
 * "parse_failed", or a thrown message) that the UI maps to a human message.
 */
export interface CaptionState {
  status: CaptionStatus;
  selectedTrack?: CaptionTrack;
  tracks: CaptionTrack[];
  cues: CaptionCue[];
  error?: string;
}

export const EMPTY_CAPTION_STATE: CaptionState = {
  status: 'idle',
  tracks: [],
  cues: [],
};

/**
 * Index of the cue active at `time` (cue.start <= time < cue.end), or -1 when
 * none matches (a gap between cues). Assumes cues are sorted by start and
 * non-overlapping (the parser guarantees this), so a binary search is safe.
 */
export function findActiveCueIndex(cues: CaptionCue[], time: number): number {
  let lo = 0;
  let hi = cues.length - 1;
  let candidate = -1;

  // Find the rightmost cue whose start <= time.
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cues[mid].start <= time) {
      candidate = mid;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }

  if (candidate >= 0 && time < cues[candidate].end) return candidate;
  return -1;
}
