import type { CaptionState } from '../shared/captions';

interface CaptionsPanelProps {
  caption: CaptionState;
}

/** Status / selected-track summary card. */
export function CaptionsPanel({ caption }: CaptionsPanelProps) {
  return (
    <section className="card">
      <h2 className="card__heading">Captions</h2>
      <CaptionsBody caption={caption} />
    </section>
  );
}

function CaptionsBody({ caption }: CaptionsPanelProps) {
  switch (caption.status) {
    case 'idle':
    case 'loading':
      return <p className="empty">Looking for captions…</p>;

    case 'awaiting_captions':
      return (
        <>
          <p className="empty">
            Spanish captions available
            {caption.selectedTrack ? ` (${caption.selectedTrack.name})` : ''}.
          </p>
          <p className="hint">
            Turn on subtitles (CC) on the video and choose the Spanish track — Lengua mirrors
            them here automatically.
          </p>
        </>
      );

    case 'not_found':
      return (
        <p className="empty">
          {caption.error === 'no_tracks'
            ? 'Captions unavailable for this video.'
            : 'No Spanish captions found for this video.'}
        </p>
      );

    case 'error': {
      const isParse = caption.error?.startsWith('parse_failed');
      const diagnostics = isParse ? caption.error?.replace(/^parse_failed \| /, '') : undefined;
      return (
        <>
          <p className="empty">
            {isParse
              ? 'Captions found, but could not be parsed.'
              : 'Captions unavailable for this video.'}
          </p>
          {diagnostics && <pre className="diag">{diagnostics}</pre>}
        </>
      );
    }

    case 'ready':
      return (
        <dl className="fields">
          <div className="field">
            <dt>Track</dt>
            <dd>{caption.selectedTrack?.name ?? '—'}</dd>
          </div>
          <div className="field">
            <dt>Language</dt>
            <dd>
              {caption.selectedTrack?.languageCode ?? '—'}
              {caption.selectedTrack?.isAutoGenerated ? ' · auto-generated' : ''}
            </dd>
          </div>
          <div className="field">
            <dt>Cues</dt>
            <dd>{caption.cues.length} lines loaded</dd>
          </div>
        </dl>
      );
  }
}
