import type { CaptionProbe, CaptionState } from '../shared/captions';
import type { VideoPlatform } from '../shared/types';

interface CaptionsPanelProps {
  caption: CaptionState;
  platform: VideoPlatform;
}

/** Status / selected-track summary card. */
export function CaptionsPanel({ caption, platform }: CaptionsPanelProps) {
  return (
    <section className="card">
      <h2 className="card__heading">Captions</h2>
      <CaptionsBody caption={caption} platform={platform} />
      {caption.probe && <ProbeReport probe={caption.probe} />}
    </section>
  );
}

function CaptionsBody({ caption, platform }: CaptionsPanelProps) {
  switch (caption.status) {
    case 'idle':
    case 'loading':
      return <p className="empty">Looking for captions…</p>;

    case 'awaiting_captions':
      return (
        <>
          <p className="empty">
            Spanish captions available
            {caption.selectedTrack ? ` (${caption.selectedTrack.name})` : ''}.
          </p>
          <p className="hint">
            Turn on subtitles (CC) on the video and choose the Spanish track — Lengua mirrors
            them here automatically.
          </p>
        </>
      );

    case 'not_found':
      if (platform === 'canalsur') {
        return (
          <p className="empty">Video detected, but no accessible captions found on this page.</p>
        );
      }
      return (
        <p className="empty">
          {caption.error === 'no_tracks'
            ? 'Captions unavailable for this video.'
            : 'No Spanish captions found for this video.'}
        </p>
      );

    case 'error': {
      const isParse = caption.error?.startsWith('parse_failed');
      const diagnostics = isParse ? caption.error?.replace(/^parse_failed \| /, '') : undefined;
      return (
        <>
          <p className="empty">
            {isParse
              ? 'Captions found, but could not be parsed.'
              : 'Captions unavailable for this video.'}
          </p>
          {diagnostics && <pre className="diag">{diagnostics}</pre>}
        </>
      );
    }

    case 'ready':
      return (
        <dl className="fields">
          <div className="field">
            <dt>Track</dt>
            <dd>{caption.selectedTrack?.name ?? '—'}</dd>
          </div>
          <div className="field">
            <dt>Language</dt>
            <dd>
              {caption.selectedTrack?.languageCode ?? '—'}
              {caption.selectedTrack?.isAutoGenerated ? ' · auto-generated' : ''}
            </dd>
          </div>
          <div className="field">
            <dt>Cues</dt>
            <dd>{caption.cues.length} lines loaded</dd>
          </div>
        </dl>
      );
  }
}

/** Collapsed developer summary of what the caption-discovery probe found. */
function ProbeReport({ probe }: { probe: CaptionProbe }) {
  return (
    <details className="probe">
      <summary>Caption probe</summary>
      <dl className="fields">
        <div className="field">
          <dt>Video element</dt>
          <dd>{probe.videoFound ? 'yes' : 'no'}</dd>
        </div>
        <div className="field">
          <dt>Native text tracks</dt>
          <dd>{probe.textTracks}</dd>
        </div>
        <div className="field">
          <dt>&lt;track&gt; elements</dt>
          <dd>{probe.trackElements}</dd>
        </div>
        <div className="field">
          <dt>Caption URLs found</dt>
          <dd>{probe.captionUrls}</dd>
        </div>
        {probe.selectedSource && (
          <div className="field">
            <dt>Source</dt>
            <dd>{probe.selectedSource}</dd>
          </div>
        )}
      </dl>
    </details>
  );
}
