import type { CaptionTrack } from '../shared/captions';

// === YouTube-internals isolation boundary =================================
// Everything that depends on YouTube's private page data lives in this module
// and youtubeCaptions.ts. If YouTube changes its internals, this is where the
// breakage (and the fix) is contained.
//
// Track discovery strategy: fetch the watch page HTML *by video id* and pull
// `ytInitialPlayerResponse` out of it. We fetch by id (rather than reading the
// live page's global) because YouTube is a single-page app — the in-page
// global is stale after client-side navigation, but a fresh fetch for the
// current id is always correct. The fetch is same-origin (www.youtube.com), so
// it carries session cookies and isn't blocked by CORS.
// ==========================================================================

interface RawCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  vssId?: string;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
}

/** Find a balanced `{...}` JSON object starting at `start` (a `{`). */
function sliceBalancedObject(source: string, start: number): string | null {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < source.length; i++) {
    const ch = source[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return source.slice(start, i + 1);
    }
  }
  return null;
}

/** Pull the `ytInitialPlayerResponse` object literal out of watch-page HTML. */
function extractPlayerResponse(html: string): unknown | null {
  const marker = 'ytInitialPlayerResponse';
  const markerIdx = html.indexOf(marker);
  if (markerIdx === -1) return null;

  const eqIdx = html.indexOf('=', markerIdx);
  if (eqIdx === -1) return null;

  const braceIdx = html.indexOf('{', eqIdx);
  if (braceIdx === -1) return null;

  const json = sliceBalancedObject(html, braceIdx);
  if (!json) return null;

  try {
    return JSON.parse(json);
  } catch {
    return null;
  }
}

function trackName(raw: RawCaptionTrack): string {
  const simple = raw.name?.simpleText?.trim();
  if (simple) return simple;
  const fromRuns = raw.name?.runs?.map((r) => r.text ?? '').join('').trim();
  if (fromRuns) return fromRuns;
  return raw.languageCode ?? 'Unknown';
}

function toCaptionTrack(raw: RawCaptionTrack): CaptionTrack | null {
  if (!raw.baseUrl || !raw.languageCode) return null;
  return {
    languageCode: raw.languageCode,
    name: trackName(raw),
    kind: raw.kind,
    isAutoGenerated: raw.kind === 'asr',
    url: raw.baseUrl,
  };
}

/**
 * Discover caption tracks for a video id. Returns [] when the video exposes no
 * caption tracks (or when the player response can't be read).
 */
export async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const res = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`, {
    credentials: 'include',
  });
  if (!res.ok) throw new Error(`watch page fetch failed: ${res.status}`);

  const html = await res.text();
  const player = extractPlayerResponse(html) as
    | { captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: RawCaptionTrack[] } } }
    | null;

  const rawTracks = player?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(rawTracks)) return [];

  return rawTracks.map(toCaptionTrack).filter((t): t is CaptionTrack => t !== null);
}

/** Spanish if the language code is es/es-* or the label names Spanish. */
export function isSpanishTrack(track: CaptionTrack): boolean {
  const code = track.languageCode.toLowerCase();
  if (code === 'es' || code.startsWith('es-') || code.startsWith('es_')) return true;
  // es-ES, es-419 covered above; also match human labels just in case.
  return /espa(?:ñ|n)ol|spanish/i.test(track.name);
}

/**
 * Pick the best Spanish track, by priority:
 *   1. Manually-uploaded Spanish captions
 *   2. Auto-generated Spanish captions
 *   3. Any Spanish track
 * Returns undefined when no Spanish track exists.
 */
export function selectSpanishTrack(tracks: CaptionTrack[]): CaptionTrack | undefined {
  const spanish = tracks.filter(isSpanishTrack);
  if (spanish.length === 0) return undefined;
  return spanish.find((t) => !t.isAutoGenerated) ?? spanish[0];
}
