import type { CaptionTrack } from '../shared/captions';

// Track-list helpers. The raw track metadata now arrives from the MAIN-world
// interceptor (captionInterceptor.ts) via postMessage, so this module no longer
// fetches anything — it just shapes and ranks tracks.

export interface RawTrack {
  languageCode?: string;
  name?: string;
  kind?: string;
}

export function mapTracks(raw: RawTrack[]): CaptionTrack[] {
  return raw
    .filter((t): t is RawTrack & { languageCode: string } => !!t.languageCode)
    .map((t) => ({
      languageCode: t.languageCode,
      name: t.name?.trim() || t.languageCode,
      kind: t.kind,
      isAutoGenerated: t.kind === 'asr',
      url: '', // cues come from the intercepted player request, not this URL
    }));
}

/** True for es / es-* language codes (es-ES, es-419) or Spanish labels. */
export function isSpanishCode(code: string | null | undefined): boolean {
  const c = (code ?? '').toLowerCase();
  return c === 'es' || c.startsWith('es-') || c.startsWith('es_');
}

/** Spanish if the language code is es/es-* or the label names Spanish. */
export function isSpanishTrack(track: CaptionTrack): boolean {
  return isSpanishCode(track.languageCode) || /espa(?:ñ|n)ol|spanish/i.test(track.name);
}

/**
 * Pick the best Spanish track, by priority:
 *   1. Manually-uploaded Spanish captions
 *   2. Auto-generated Spanish captions
 *   3. Any Spanish track
 * Returns undefined when no Spanish track exists.
 */
export function selectSpanishTrack(tracks: CaptionTrack[]): CaptionTrack | undefined {
  const spanish = tracks.filter(isSpanishTrack);
  if (spanish.length === 0) return undefined;
  return spanish.find((t) => !t.isAutoGenerated) ?? spanish[0];
}
